---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: qdrant-secrets
  namespace: apps
spec:
  encryptedData:
    QDRANT__SERVICE__API_KEY: AgBs03MuEuL5drNs5j5qysOrkSszErKUvCF5mcCj7VfgUhRIQELbQ2ynuliffg3IVYpVY4qCszphtBuMWG6xIZyW7EM6ima+ZG2fh6SAYj9uA+WQicA2z0IjgEZQACHGaxaTIUsXD3bE0ghSDZ7aOHS4rnjEcBEyulI/JQRJsSTf9V5HL8B/fal/OLfKdcpbWt/O82bBBFuK651Y8VKSsMsciWRmXD3Js1pwnHKBCrAcn6FqWzvi6oRTQUDaxGU8Qy6sfA3gaC1vBa3B7cvsQluTzPah7j0kmMs/eO5vlEI+lvjbqf9IOmIad+BQQYx+hwOWM9zFX0/JbrQcSOfpBQLmjfsJBcWL9rvDZI02AzvDkUxeI8LxrkZymifjMxk03uSHrvKHrxYYdBSKRTKofeU0yrmmxQkfDem6oURFl1T4To58NyBr/s3me2ddZ4411ENA0TFS0S6PuECioA6KCRZSlG6PLSohgwhlAT7B6lDlm+0m2wMQn29RVrHLA6FVH4UGK/PiAcJY+7PLtY70hkmjKDGTfOebAO4wpvMhUMuZ0G+Ofkqbk9bGSg+1LoDxzxmnl33LpdBfnnA+08WmU3/r2hXmGgPzTBL8R2mnX7VWxL+vhBxzq1OK1gQ1mrJjPVyyUTcRg/V9Re+EKbZsrUGW1kdSbIkVqZwlXZin5AQ/+g0ykiQSvpULtW3rTF7cMlCtgZTwdDl5RX51aX9FqiHUOEdDU9LmZ1oL6ruxfIBVgS3kEWJDLY1FTUihACUcb3F1cdY5s2tRc+A8e7WDL7xI
  template:
    metadata:
      creationTimestamp: null
      name: qdrant-secrets
      namespace: apps
