---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qdrant-secrets
  namespace: apps
spec:
  encryptedData:
    QDRANT__SERVICE__API_KEY: AgBq3kjIdISZ0c1MGN+BTsK0XX/WTvg7IrTXZzpHbZ6m5IHNTYACWdv/o69wuKE5E3zsScCv6DGsHaPPlAu1QgJ3qvvvMYkJ38nvfPQBONxhbSZ/FGcz6WlIIDuk3T4Y1W7nFOZJk1LEvAPHZ9PY3LTPXnaG19OAyJd3ZTa++Rog96qVNQIf/CpMr53HkllpgK7iRW7rqsJoZUCvXApnfN78mlWM4vfU3+GKpJ0G+9RTQpJzYJixXQHHeXX1XGkK4034rD8r2j2jq/DkIT2E+r2kmxcytM2RJ5F30aFM34y4LE/XpGUHx1MWkd9L6lPNk3O/UnXt/S5THCBxLkff8NqTD/hoz4sXiozGFrjF9HTIvxRdlYzU0zbwXJPC/ojOJfdeujsEck71pX+X30zHbyRtibIZ0o8nOMQjUyO4JVXYIQGw6LxMtH+vGojV1NS44qOFUh0/lZVwdo8RPpuyqy3YllKKi49ir9wNEDXt/xCwXJtBUyM2dB5NLjuwaO0dNkWL/+wOVjmXbIkYvK3mVlik/ETHiaGRrBCdAd5VyQ7ZiTc04RF4TGwPSJioRpuFfsIOnt9yG/o+6M2ndyh6PbxNH74JCwJGCrcHWoi8m271AzUkU1TVzJ2SOkLlmbA2CPWrkJ0IBeQuikiwfME/5jdMNBCJ1TWC5oIjmt59BGfkMbThOKI7Tw0tNAjcKE+wkbYD8IvWwHeIwkImPbJdVZUtCX5iJYMl6YbSva03GXAlXDLjQqECaNR9
  template:
    metadata:
      name: qdrant-secrets
      namespace: apps
