apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgBDcN7dz07+1nZEgFV7WDgZSkKo2rnykfhde9coKoYI88v/it4IL644POZasjQij2UNZrvQ4N5at8Vw337FtiF1l3krZoCHi8S5xElVa0R2yv62m2lFr/AfllttGIe3rHPCE3Io8v9hMR/2EJmL8rqHCSEsMjGmFgbsJP5yxl32ttJwlNhpx1/2cQuuQrHI47fCkrVFpMyxnHZa2vE6bCMgsjjFlMuLGQlt6FoocnDhh+mlgqi0pP8tKU5e30IsxAMZcCTlagyiZFLMScem7fsb/ZvesB2vFNrmMSrDkeCNFsT8DBZx+GPSoKR1XHZyg9+vkFRJBwKmizcSOXH2fTSThSZNCW34RmrBl+B0zTki7H/jt6HeU06+ww/kpNM59IbgZLysg2osxUhqYIhdZPeedIJThCHJNEDxJ5FD5K38pGFZlHL55s4xyHUPeQ8lwG36TIn9zsUa/HrhTz7zCuUODNun+19j1AD9DYJjbTu8xTh/xbL3k1jVfX3WmJ4Zy2fe9NprllOilG78SFB3HG8MPy1iViro8DB+3NpsMTXLQ7T1c8mOwlF2gQ6XjTe2UxXtECX2Wg2KL+BnRh7Ok29OR6XVAqAF+lHz6naXYbT8NJWPkyrQr276a075tY+Wdkchuv6M/2iiH3ynz4NcI6MPJn+wewpLsitDjt8YK0ZzdSHwDvw/CWhDvvKNbuAVonkujwVJPrdtfVp9o77ZHnqNtcbg0MOVB6e15ewDCYulhvGdYB3nz4n7ter2em6u8C0FGTfjopCwvVj8FhCwltKD7e4dw7TAt+9p7CdRazKLDIW9YWK7tNhGadlQ182y7VM6s/m5EsbVc33bnEPtNsL7CHbq7atY/gmKOH7J1sMuXm1LxZpurPmgZOh98x3gyajdGMCilBDqiBD+FOd+abltGoMNrqOvVmKfHaliBpgETaxOCqFxuhKrMwk=
  template:
    metadata:
      name: ghcr-credentials
      namespace: apps
    type: kubernetes.io/dockerconfigjson
