---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-secrets
  namespace: apps
spec:
  encryptedData:
    MLFLOW_DB_PASSWORD: AgBS6igiK3Q1x6WPGsbMBiwaUMeEHialOxtkICOMEPUHRzRxIyKmPu8JQ0616XT87mqgpi1c9v62n3ABbwo02718qi4BsvnRtoC3ct91DLC2ze2Ls8NEaC3XrJ0RbVgJs7mWF9m7kmK6tcJs6ZFKjzsEcFluDjdZPYozu8NwS/6YvVSLqGgdhr6MJNJ4T6MoHaFe6ywnJoYLoG6s3BBbM7RgQlF4MSYsncja6M2Bl9D0x1SMTZH0tAVqPI5nvtw8B60FZ/V1XNglOsM9b1Jib7//r5dZjbuuoFfsjYLQV8ZUZ2NZFylrtMSx2hvri5Q6k58p6kmpa+hLg3SDATrA8YSYEIWLgk8BDZWD/vobmgrh++0JUy2nM57ut0/swTidxeDgCcIdJCLTk0TX1m5ZO5GvQEitjP9wvBEx/KAwPXYCGUuw+5foXevxI6P1HD+PswQ1N6szvuOWVmN86bfx6il3SsI25QS76YvhK8PX3DR2QcMffosrQRgxcQtaQwFuIQKjcG+uCH3MVPbjZHvACTlvgGVXAVp6i9U2N0KOimsrAm/0eusPrN/+dcolnl6gKz/utaYbBtMI44B/oLyMvLm9cqapQAsH+QfuYe+0DKW+0deq96cpL6V8zpnx0Gb6RDizztP1ntMUbGPynpFRo6fOqMlAegnglNzjeaSq79wE6NjmIS4KCYLcKNtxvbpzqoGCdBAndwN1zaEvHE6A0DqaCza8qjQWrCk7/ic6RI5Lzw==
  template:
    metadata:
      name: mlflow-secrets
      namespace: apps
