---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mlflow-secrets
  namespace: apps
spec:
  encryptedData:
    MLFLOW_DB_PASSWORD: AgBfvN4V0MJRQhyfpeds6gF5mZHrnsvNrwWeezJ+hmWFZ+nLiX4iSSBoOe1wHi8ZSWfY8lHbopAlrwCCVYD2p1uKUx9a+byfj62ESVc/kg1yaBuisvmVKZd0fcT3XQvfb1e+q/x+2w0475jZwJRihRZ6pn2PSoAI0Jy7K3FJXKZm4jRTse/VlGSSj3tFyP9tfV2tdYNRv/j2aIPw0t+nXmmk+DIpil0Hd8FeybeEhMYx6fM1J1SEMXgOpUiU/D6dpW6feUFLBk19/Uj2anbAU07kAyAR2ep7dTi4VSyut/pNHy44tuETJLY2Zxl60WsNM/+hJnZMy5bVLWt4qC7wxJaZm7NOQxdKZHV0J8o8wuIQsSKV1dUIGUeP/hTvdv7I0fAPrATvV6e+FXYxPAXcqxm1QNVuYKmrZrdFoJjtE9TGtW/KRbG/tAAVC/h1NFAofZFbW3mo0CFHH4RohtDKVFiWD7OlHensxsuHPCV0Z4oliJBThJO0RPRUTGXbKefe6EwMI3Oj166t8ux4NIYTY3YOyIJlMuOzGVySBUwnnKi7Qmy9Dgmnjamx5AUHmXWBdDA0nrkOY/NyIIF2xgPSfFQrdnDb1j1VlJ55HoKSU2VOIshdCgubXklGh9d1TaTJR02uyFnuFg0lO5rrIrdBJZkMaWsuoRE+tCI5yrE/ImMbhnx8ud+J6exz2PMYezHta6MhCIS9FGVL6T/g/cGYLlZGMpGEOd0Kp7Pb0p8buV1jWg==
  template:
    metadata:
      creationTimestamp: null
      name: mlflow-secrets
      namespace: apps
