---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgDZCYuuOzUZdYKriT6AmHeo5uOk+qSXZzkokgkycVVjarVjZ3znfW9wk3vVzXk4ZObPCP43Rqv2Rvwm11GfIOJFcI/uRx/PyErnKtkFxtVvOj7qqTrtna7GHcduBAj11ui9cS3VBnGE85ks4aaKJ9GAdFS5LCmtjMpdvk5oaAOs4edZij9eOa/4D6XuUJbOoGzxGiA+SzWFfM3TOAgtpqLH368hp78Q8kLDMbJWWBRuLYUZyRCKJ6PsYI/iM6qFoN92fgBJrmvR7+H/ezWCdqVQlEDbjfLGeonqhECAlknDdz9+HoGN+EmQnBezGecH8wnB/64ckqMzrjWpghpIb3m/JqSDPMpTaRXCO3frKejyhPWN/ZfLbP+sv1D1nvgdb3reefzckLBA++2ak4Oz76glm0/YGFvpgUuCftpDVa2Y/wssfT0fMBaGlboNcy3z6/ySK6iF5fCYRqfpsEQVyIpXWbhnRdGKsz07DatjX5aumupEI9iVnvj4apHW0m0vVxoTnVEMEO+alNgP3SSHuFWkKc5FPRSXHOrCaCQlYGeNtgtXmwcHkBgtRRW8RW9wfUIyeyCtRt1H/q2p8luWbTI27RSgWPcjYlMSDi1RhItdyr3e81cqvuq6jNvT5koIIYXqcM3/OmwA4nKq62NOEWc+lzIK0JpQlcenVP8TRbPxSxL0i+skW0gUua6aqRll7BKI4S7sAI0Z7+9lpNZAUwcvZ3uZuWKjpVSU/asKCimkAxKS5E8jup9w
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAgUd9laRI4sEs4VTDtd/aHfYIh9ff2okFY8t76CbQgvgtOrYV/KwCFSrNe6G5q1TseGR9k/fIRgoPE5azNiiEBYXAMMSeUWddHpU5IGT3MN2y4rJxg0yi45Pib9IA4fm80p2TDk9riLUGF5iO61EiLuoBzh2zoCsehxrehn/wdEww9tlrxSIBKHP+nQ4SsuRn6JAaElzJKsVCkEKXYK7e3AfFfAQlpvK8KNzV8Tk/LLAudv1H+5XMgaZppU1Xw3CXt8UxZbtRry32AdL3qXytSUoI11IaKx3VxICZ1dj4uRg0asijltW2sa5h38VS5ozmBBzeF3Kt6HZR98BPAL3w6ZyQh+0Hce5zoHeuKoOjVOLf93M/yDxED6TfBCKuHF5dNE3HB0XOjSiBqjuQaOZ9jY92O7xGNMMNuXCU6XEPB2YqZinLeJEy/K+w3erOgRvYm+jfVXwX0cU0mbhvdhiJFYlJeSYoIhAGP+Br/vWbKG05Xnako/llRTbHUEMT4Czl/SA2UbpfCdydrgU/XrptOY9boT1lCp9ilHiXcgxNPwavsVL7g9SMeVBE23Mm84AGiTLO96Dtuw6c1cBaNNSVQuS+Wbpn9WRqGm2thjskSpwAZ9OoYAv+W0EKO6mquzS0rci9Fl7hvFMgAYHnnX+bD0fNBJdLSMuZPfywYMMgcSZ+7/x5bQA7ZYljTbeihZ3TOX7sdh36Xykl8lprf9kmazxBcNRweBlx3ViIJvafofwDaa29GH/g2+bGiGR5Du+Dtao03dGIjCRuSWUI/yloHq7BhUpWBQqz8fhgnpurQeMIPRo+aBPvvU99Y62XdCR1aYltTyKeDGeWGbU7qo0xD1eqZ+ao1KxJXznPpgyumZw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oidc
      namespace: monitoring
