apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-lab
  namespace: infra
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: ai-lab
  source:
    repoURL: git@github.com:aymenmastouri/k8s-manifests.git
    targetRevision: main
    path: apps/ai-lab
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
